### ISSUE TITLE
can start TimeCrowd from Slack

### ISSUE THREAD

**Issue by yuitnnn** [pandeiro245/forgettable#12]
# 前提
## オペレーション
* SlackとTimeCrowdで同じメールアドレスを設定することを義務付ける

## API仕様
* TimeCrowdもSlackもAPI経由でメールアドレスを取得できる

# TODO
## 事前設定
* [ ] Slackのテナント or チャネルとTimeCrowd上のチーム or カテゴリ を紐付ける（デフォルト設定もできる）

## 招待
* [ ] 下記のslackからのTC打刻を実行する際、該当Slackアカウントのメールアドレスが該当TCチームのメンバー上に存在しない場合、API経由で招待する。
* [ ] 上記の際、API経由でも存在しない場合はSlackにエラーを返す 

## 日々の打刻
* [ ] `/tc [タスク名] `でスタート
* [ ] `/tc https://github.com/pandeiro245/forgettable/issues/12` みたいにURLでも打刻できる
* [ ] `/forgettable todo` で自分のアサインされているgithub issuesが表示されてそこアクションボタンでもStartできる
* [ ] 上記を実行するとSlackのアクションボタンとしてStart / Stopボタンが出現してかつ、稼働時間（その回、累計）をpost
* [ ] 上記を実行するとSlackのアクションボタンとしてStart / Stop ボタンが出現

※毎回 Start / Stop両方出すのは他のメンバーも同じタスクをTC Start / Stopしたい可能性があるため
※Slackにはメッセージ毎にチャネル全員が見れる or その人だけ見れる が設定できるので全部出すのはごちゃごちゃする場合はれを使う？
