### ISSUE TITLE
TimeCrowd -> Misoca

### ISSUE THREAD

**Issue by bls600qm** [pandeiro245/forgettable#15]
# TODO
* [ ] 開発用のTimeCrowdアカウント取得
* [ ] TimeCrowdのレポートAPIで指定月の打刻データを取得する：https://timecrowd.net/apidoc/v1/reports.html
* [ ] 開発用のMisocaアカウント取得
* [ ] Misoca OAuthトークン取得
* [ ] API経由で請求書発行
* [ ] API経由でメール送付

# APIを使わずブラウザで行なった場合
* [ ] Misocaにログイン
* [ ] 請求書作成を押す
* [ ] 請求先を入れる
* [ ] 支払期日を入れる
* [ ] 名目を入れる
* [ ] 金額を入れる
* [ ] PDFをEmail経由で送る

**Comment by bls600qm** [comment]
<img width="898" alt="2018-09-01 15 28 10" src="https://user-images.githubusercontent.com/28918192/44943109-c0551c80-adfb-11e8-912f-e5badb6cd094.png">

名目部分はこんな感じ

**Comment by zu-min** [comment]
Misoca API : http://doc.misoca.jp

**Comment by zu-min** [comment]
#10 の実装で omniauth 関連がはいるので， Misoca のOAuth認証も乗っかれば良さそう

**Comment by zu-min** [comment]
- [ ] TimeCrowd OAuth Login
- [ ] Misoca OAuth Login
- [ ] TimeCword API wrapper
- [ ] Misoca API wrapper
- [ ] 請求書API用データ成形
- [ ] Mail送信

請求書用データ形成部分で，MisocaとかBill Builderとか請求書作成サービス名を指定して成形してから，wrapperに投げるといい感じになりそう

**Comment by zu-min** [comment]
Misocaで請求書を作成したことがある場合，請求先が登録されている。
```
請求先をAPIから取得して請求書を作成する時に，
請求先が存在する場合 -> 請求先を選択して請求書を作成
請求書が存在しない場合 -> 請求先の選択はせずに請求書を作成
```

作成した請求書は，APIからBase64エンコードされたPDFで取得可能。

**Comment by zu-min** [comment]
refs #26 
MisocaとTimeCrowdに関する環境変数がこのissueで増えるので，PR作成時に同時に解決することにする

**Comment by zu-min** [comment]
- Misoca API の請求書作成では，請求書送付者の情報も送ることができるが，このissueではMisocaに自社情報は設定済みという想定で，開発を進めることとする
