### ISSUE TITLE
create masked data from kintone

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/forgettable#29]
# TODO
* [x] add a kintone gem: https://github.com/mashupwork/kintone_sync
* [x] add a setting app of kintone
* [x] fetch production data
* [x] masking
* [x] save masked data
